### PR TITLE
661 | feat (cli query): improve error handling

### LINKED ISSUE #661: CLI: `w3 query ...` Should Return Non-Zero Error Code When Query Fails
Currently when an error throws an error, the CLI still returns a 0 exit code, meaning that automated CI steps think it succeeded successfully.

### PR DESCRIPTION
**Pull request by arcbjorn**

### CODE REVIEW

File: packages/cli/src/commands/query.ts [hunk 1]
```diff
@@ -226,6 +226,10 @@ export default {
             print.error("-----------------------------------");
           }
         }
+
+        if (errors) {
+          process.exitCode = 1;
+        }
       }
```
Comment (Niraj-Kamdar) [inline packages/cli/src/commands/query.ts]: Why another condition? We should add this after printing errors

**Review by Niraj-Kamdar — CHANGES_REQUESTED** [review]

File: packages/cli/src/commands/query.ts (hunk 1 above)
Comment (arcbjorn) [reply packages/cli/src/commands/query.ts]: Yes, did some experimenting with types. Fixed now, thank you

**Review by dOrgJelli — APPROVED** [review]
