### PR TITLE
Use Result type and throw fewer errors in Client and Core

### LINKED ISSUE #1018: Client: Throw Less Errors
In the JS client + core libraries, we throw errors. This is a hard error handling method to develop against, because you do not know what functions will throw and which will not. Treating all functions as "throwable" is not very realistic.

Instead we can adopt a better strategy, return wrapped result + error objects (aka `Result<T>`).

This is a well known development practice that we use in all of our wasm languages.

### LINKED ISSUE #1245: Use Result type from @polywrap/result instead of InvokeResult
The InvokeResult type returned from invocations is defined as follows:
```typescript
/**
 * Result of an Wrapper invocation.
 *
 * @template TData Type of the invoke result data.
 */
export interface InvokeResult<TData = unknown> {
    /**
     * Invoke result data. The type of this value is the return type
     * of the method. If undefined, it means something went wrong.
     * Errors should be populated with information as to what happened.
     * Null is used to represent an intentionally null result.
     */
    data?: TData;
    /** Errors encountered during the invocation. */
    error?: Error;
}
```
It should be replaced with the Result type from @polywrap/result to get better type checking from TypeScript
```typescript
export type Result<T, E = undefined> =
  | { ok: true; value: T }
  | { ok: false; error: E | undefined };
```

### PR DESCRIPTION
**Pull request by krisbitney**
This PR replaces most thrown errors in the client and core with the `Result` pattern. Notably, `client.invoke` now returns a `Result<TData, Error>`.

Closes https://github.com/polywrap/toolchain/issues/1018, https://github.com/polywrap/toolchain/issues/1245

### CODE REVIEW

**Review by dOrgJelli — DISMISSED** [review]

File: packages/js/client/src/PolywrapClient.ts [hunk 1]
```diff
@@ -202,7 +215,7 @@ export class PolywrapClient implements Client {
   >(options: QueryOptions<TVariables, TUri>): Promise<QueryResult<TData>> {
     let result: QueryResult<TData>;
 
-    try {
+    err: try {
```
Comment (cbrzn) [inline packages/js/client/src/PolywrapClient.ts:221]: Just curious here: What's the reason for this syntax? I am noticing that you are then using a break but we can also return `{ errors: [parseResult.error as Error] }`? Probably I am wrong but just wanted to understand this :P

File: packages/js/plugins/uri-resolvers/ens-resolver/src/index.ts [hunk 2]
```diff
@@ -125,22 +125,22 @@ export class EnsResolverPlugin extends Module<EnsResolverPluginConfig> {
...
           );
         }
 
-        return data;
+        return result.value;
       }
 
       throw Error(
-        `Ethereum.callContractView returned nothing.\nData: ${data}\nError: ${error}`
+        `Ethereum.callContractView returned nothing.\nData: \nError: `
```
Comment (cbrzn) [inline packages/js/plugins/uri-resolvers/ens-resolver/src/index.ts:143]: Should we have the `\nData: \nError:`? Might be miss leading but not sure

File: packages/js/core/src/algorithms/get-implementations.ts [hunk 3]
```diff
@@ -24,9 +25,19 @@ export const getImplementations = Tracer.traceFunc(
...
-          ? applyRedirects(interfaceImplementations.interface, redirects)
-          : interfaceImplementations.interface;
+        let fullyResolvedUri: Uri;
+        if (redirects) {
+          const redirectsResult = applyRedirects(
+            interfaceImplementations.interface,
+            redirects
+          );
+          if (!redirectsResult.ok) {
+            continue;
```
Comment (nerfZael) [inline packages/js/core/src/algorithms/get-implementations.ts:35]: Why are we ignoring the error here instead of returning it?

**Review by cbrzn — DISMISSED** [review]
This is super cool :) Feel free to ignore my comments

File: packages/js/plugins/logger/src/__tests__/e2e/e2e.spec.ts [hunk 4]
```diff
@@ -13,8 +13,8 @@ describe("log method", () => {
       },
     });
 
-    expect(response.error).toBeUndefined();
-    expect(response.data).toBeDefined();
-    expect(response.data).toBe(true);
+    if (!response.ok) fail(response.error);
+    expect(response.value).toBeDefined();
```
Comment (nerfZael) [inline packages/js/plugins/logger/src/__tests__/e2e/e2e.spec.ts:17]: I think this one is redundant

**Comment by nerfZael** [comment]
@krisbitney  PR looks awesome! I left a couple comments and there's some minor fixes in this PR: https://github.com/polywrap/toolchain/pull/1285

File: packages/js/client/src/PolywrapClient.ts (hunk 1 above)
Comment (krisbitney) [reply packages/js/client/src/PolywrapClient.ts:221]: It's because of the `clearContext` below the try catch statement. I wanted to be sure it still ran since it was running on error before the changes.

File: packages/js/plugins/uri-resolvers/ens-resolver/src/index.ts (hunk 2 above)
Comment (krisbitney) [reply packages/js/plugins/uri-resolvers/ens-resolver/src/index.ts:143]: I went back and forth on this. Ultimately I decided not to change the behavior.

File: packages/js/core/src/algorithms/get-implementations.ts (hunk 3 above)
Comment (krisbitney) [reply packages/js/core/src/algorithms/get-implementations.ts:35]: I was just trying not to change the behavior.

Comment (nerfZael) [reply packages/js/core/src/algorithms/get-implementations.ts:35]: Isn't the previous implementation to throw an error here, but the current to silence it?

Comment (krisbitney) [reply packages/js/core/src/algorithms/get-implementations.ts:35]: if so, I made a mistake!

Comment (krisbitney) [reply packages/js/core/src/algorithms/get-implementations.ts:35]: You're right. The old implementation looked like this:
```
  const fullyResolvedUri = redirects
    ? applyRedirects(interfaceImplementations.interface, redirects)
    : interfaceImplementations.interface;
```
And applyRedirects threw errors. Good catch!!!

Comment (krisbitney) [reply packages/js/core/src/algorithms/get-implementations.ts:35]: I fixed it in this PR: https://github.com/polywrap/toolchain/pull/1288

Comment (nerfZael) [reply packages/js/core/src/algorithms/get-implementations.ts:35]: Great!
